# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3119feb92e48a8aa8404737ab9006d7bf1df5f1dc41e471b697086211b78699cca172b9e6409307c9ce9504c5f04b14ffdc79e1bef97f936e51a27116f17d1bc
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>

test:
  secret_key_base: b80e24e12248b3a0813db35697236499cf9021a9c4932f8ea3b1b66634d6c545d2f4186c5772f1bc97f04a56a1a686aebf1ae6dd8e49beb584fe235f2090872b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV["MANDRILL_USERNAME"] %>
  email_provider_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
